In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
df = pd.read_csv("retail_sales_dataset.csv")
df

    Customer ID  Gender  Age Product Category  Quantity  Price per Unit
0       CUST001    Male   34           Beauty         3              50
1       CUST002  Female   26         Clothing         2             500
2       CUST003    Male   50      Electronics         1              30
3       CUST004    Male   37         Clothing         1             500
4       CUST005    Male   30           Beauty         2              50
..          ...     ...  ...              ...       ...             ...
995     CUST996    Male   62         Clothing         1              50
996     CUST997    Male   52           Beauty         3              30
997     CUST998  Female   23           Beauty         4              25
998     CUST999  Female   36      Electronics         3              50
999    CUST1000    Male   47      Electronics         4              30

[1000 rows x 6 columns]

On Retail Sales Dataset

Level 1 – Basic
Create a UDF to calculate Total Amount as Quantity × Price per Unit.

In [6]:
def total_amount(Quantity,Price_per_Unit):
    return Quantity * Price_per_Unit
df['Total_Amount'] = total_amount(df['Quantity'], df['Price per Unit'])
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount
0,CUST001,Male,34,Beauty,3,50,150
1,CUST002,Female,26,Clothing,2,500,1000
2,CUST003,Male,50,Electronics,1,30,30
3,CUST004,Male,37,Clothing,1,500,500
4,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50
996,CUST997,Male,52,Beauty,3,30,90
997,CUST998,Female,23,Beauty,4,25,100
998,CUST999,Female,36,Electronics,3,50,150
999,CUST1000,Male,47,Electronics,4,30,120

Create a UDF that categorizes Age into:

Young (<25)
Adult (25–45)
Senior (>45)

In [16]:
def myf(u):
    if u < 25:
        return 'Young'
    elif 25 <= u <=45:
        return 'Adult'
    else:
        return 'Senior'
df['Age_group'] = df['Age'].apply(myf)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group
0,CUST001,Male,34,Beauty,3,50,150,Adult
1,CUST002,Female,26,Clothing,2,500,1000,Adult
2,CUST003,Male,50,Electronics,1,30,30,Senior
3,CUST004,Male,37,Clothing,1,500,500,Adult
4,CUST005,Male,30,Beauty,2,50,100,Adult
...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior
996,CUST997,Male,52,Beauty,3,30,90,Senior
997,CUST998,Female,23,Beauty,4,25,100,Young
998,CUST999,Female,36,Electronics,3,50,150,Adult
999,CUST1000,Male,47,Electronics,4,30,120,Senior


Create a UDF that converts Product Category into single-letter codes:

Beauty → B
Clothing → C
Electronics → E

In [21]:
def Code (y):
    if y == 'Beauty':
        return 'B'
    elif y == 'Clothing':
        return 'C'
    else:
        return 'E'
df['Category_code'] = df['Product Category'].apply(Code)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code
0,CUST001,Male,34,Beauty,3,50,150,Adult,B
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C
2,CUST003,Male,50,Electronics,1,30,30,Senior,E
3,CUST004,Male,37,Clothing,1,500,500,Adult,C
4,CUST005,Male,30,Beauty,2,50,100,Adult,B
...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C
996,CUST997,Male,52,Beauty,3,30,90,Senior,B
997,CUST998,Female,23,Beauty,4,25,100,Young,B
998,CUST999,Female,36,Electronics,3,50,150,Adult,E
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E

Create a UDF that converts Gender:

Male → 1
Female → 0

In [23]:
def gender (g):
    if g == 'Male':
        return 1
    elif g == 'Female':
        return 0
df['gender_code'] = df['Gender'].apply(gender)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1
...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1

Level 2 – Medium
Create a UDF that classifies orders:

Quantity ≥ 3 → High Order
Otherwise → Low Order

In [25]:
def classified_order (o):
    if o >=3:
        return 'High Order'
    else:
        return 'Low Order'
df['Order_code'] = df['Quantity'].apply(classified_order)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order
...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order

Create a UDF that creates price bands:

<100 → Budget
100–300 → Mid Range
300 → Premium

In [27]:
def price_band (p):
    if p <100 :
        return 'Budget'
    if 100 <= p <=300:
        return 'Mid Range'
    else:
        return 'Premium'
df['Price_band'] = df['Total_Amount'].apply(price_band)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range
...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range


Create a UDF that extracts the numeric part from Customer ID (CUST014 → 14) and returns the number of digits.

In [30]:
def digit_find(d):
    num = d.replace('CUST','')
    return len(num)
df['Digit'] = df['Customer ID'].apply(digit_find)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band,Digit
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range,3
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium,3
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget,3
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium,3
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget,3
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget,3
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range,3
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range,3
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range,4

Level 3 – Row Based

Create a UDF to calculate a Business Score:

Score = (Age / 2) + (Quantity × 5)

In [31]:
def Business_score(row):
    score = (row['Age']/2) + (row['Quantity']*5)
    return score
df['Business_score'] = df.apply(Business_score,axis = 1)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band,Digit,Business_score
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range,3,32.0
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium,3,23.0
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget,3,30.0
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium,3,23.5
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range,3,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget,3,36.0
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget,3,41.0
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range,3,31.5
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range,3,33.0
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range,4,43.5

Create a UDF that assigns product appeal:
Clothing and Age < 30 → Youth Appeal
Beauty and Age > 45 → Mature Appeal
Otherwise → General Appeal

In [35]:
def product_appeal (row):
    if row['Product Category'] == 'Clothing' and row['Age'] <30:
        return ('Youth Appeal')
    elif row['Product Category'] == 'Beauty' and row['Age'] <45:
        return 'Mature Appeal'
    else:
        return 'General Appeal'
df['Assign_product_appeal'] = df.apply(product_appeal ,axis =1)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band,Digit,Business_score,Assign_product_appeal
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range,3,32.0,Mature Appeal
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium,3,23.0,Youth Appeal
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget,3,30.0,General Appeal
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium,3,23.5,General Appeal
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range,3,25.0,Mature Appeal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget,3,36.0,General Appeal
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget,3,41.0,General Appeal
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range,3,31.5,Mature Appeal
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range,3,33.0,General Appeal
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range,4,43.5,General Appeal

Level 4 – String Processing

Create a UDF to extract only the numeric portion from Customer ID (CUST009 → 9).

In [36]:
def extract (i):
    number = i.replace('CUST','')
    return int(number)
df['extrcat_number'] = df['Customer ID'].apply(extract)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band,Digit,Business_score,Assign_product_appeal,extrcat_number
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range,3,32.0,Mature Appeal,1
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium,3,23.0,Youth Appeal,2
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget,3,30.0,General Appeal,3
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium,3,23.5,General Appeal,4
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range,3,25.0,Mature Appeal,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget,3,36.0,General Appeal,996
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget,3,41.0,General Appeal,997
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range,3,31.5,Mature Appeal,998
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range,3,33.0,General Appeal,999
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range,4,43.5,General Appeal,1000

Create a UDF to mask Customer ID so only the first two characters are visible (CUST009 → CU****).

In [37]:
def mask_customer_id ( id):
    return id[:2]+'****'
df['masked_id'] = df['Customer ID'].apply(mask_customer_id)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band,Digit,Business_score,Assign_product_appeal,extrcat_number,masked_id
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range,3,32.0,Mature Appeal,1,CU****
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium,3,23.0,Youth Appeal,2,CU****
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget,3,30.0,General Appeal,3,CU****
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium,3,23.5,General Appeal,4,CU****
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range,3,25.0,Mature Appeal,5,CU****
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget,3,36.0,General Appeal,996,CU****
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget,3,41.0,General Appeal,997,CU****
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range,3,31.5,Mature Appeal,998,CU****
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range,3,33.0,General Appeal,999,CU****
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range,4,43.5,General Appeal,1000,CU****

Level 5 – Business Logic


Based on Total Amount, create a UDF to assign Purchase Tier:
<500 → Bronze
500–1500 → Silver
1500 → Gold

In [38]:
def Purchase(v):
    if v < 500:
        return ' Bronze'
    elif 500 <= v <= 1500:
        return 'Silver'
    else:
        return "Gold"
df['Product_tier'] = df['Total_Amount'].apply(Purchase)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band,Digit,Business_score,Assign_product_appeal,extrcat_number,masked_id,Product_tier
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range,3,32.0,Mature Appeal,1,CU****,Bronze
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium,3,23.0,Youth Appeal,2,CU****,Silver
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget,3,30.0,General Appeal,3,CU****,Bronze
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium,3,23.5,General Appeal,4,CU****,Silver
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range,3,25.0,Mature Appeal,5,CU****,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget,3,36.0,General Appeal,996,CU****,Bronze
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget,3,41.0,General Appeal,997,CU****,Bronze
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range,3,31.5,Mature Appeal,998,CU****,Bronze
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range,3,33.0,General Appeal,999,CU****,Bronze
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range,4,43.5,General Appeal,1000,CU****,Bronze

Create a UDF to assign discount percentage:
Age < 25 → 10%
Price per Unit > 300 → 15%
Otherwise → 5%

In [40]:
def discounting (row):
    if row['Age'] < 25:
        return '10%'
    elif row['Price per Unit'] > 300:
        return '15%'
    else:
        return '5%'
df['Discount_percentage'] = df.apply(discounting ,axis = 1)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band,Digit,Business_score,Assign_product_appeal,extrcat_number,masked_id,Product_tier,Discount_percentage
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range,3,32.0,Mature Appeal,1,CU****,Bronze,5%
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium,3,23.0,Youth Appeal,2,CU****,Silver,15%
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget,3,30.0,General Appeal,3,CU****,Bronze,5%
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium,3,23.5,General Appeal,4,CU****,Silver,15%
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range,3,25.0,Mature Appeal,5,CU****,Bronze,5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget,3,36.0,General Appeal,996,CU****,Bronze,5%
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget,3,41.0,General Appeal,997,CU****,Bronze,5%
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range,3,31.5,Mature Appeal,998,CU****,Bronze,10%
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range,3,33.0,General Appeal,999,CU****,Bronze,5%
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range,4,43.5,General Appeal,1000,CU****,Bronze,5%

Create a UDF to calculate Final Bill:
Final Bill = Total – (Total × Discount%)

In [41]:
df['Discount_percentage'] = df['Discount_percentage'].str.replace('%','').astype(float)
def final_bill(row):
    return row['Total_Amount'] - (row['Total_Amount']* row['Discount_percentage']/100)
df['Final Bill'] = df.apply(final_bill, axis=1)
df

,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total_Amount,Age_group,Category_code,gender_code,Order_code,Price_band,Digit,Business_score,Assign_product_appeal,extrcat_number,masked_id,Product_tier,Discount_percentage,Final Bill
0,CUST001,Male,34,Beauty,3,50,150,Adult,B,1,High Order,Mid Range,3,32.0,Mature Appeal,1,CU****,Bronze,5.0,142.5
1,CUST002,Female,26,Clothing,2,500,1000,Adult,C,0,Low Order,Premium,3,23.0,Youth Appeal,2,CU****,Silver,15.0,850.0
2,CUST003,Male,50,Electronics,1,30,30,Senior,E,1,Low Order,Budget,3,30.0,General Appeal,3,CU****,Bronze,5.0,28.5
3,CUST004,Male,37,Clothing,1,500,500,Adult,C,1,Low Order,Premium,3,23.5,General Appeal,4,CU****,Silver,15.0,425.0
4,CUST005,Male,30,Beauty,2,50,100,Adult,B,1,Low Order,Mid Range,3,25.0,Mature Appeal,5,CU****,Bronze,5.0,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,CUST996,Male,62,Clothing,1,50,50,Senior,C,1,Low Order,Budget,3,36.0,General Appeal,996,CU****,Bronze,5.0,47.5
996,CUST997,Male,52,Beauty,3,30,90,Senior,B,1,High Order,Budget,3,41.0,General Appeal,997,CU****,Bronze,5.0,85.5
997,CUST998,Female,23,Beauty,4,25,100,Young,B,0,High Order,Mid Range,3,31.5,Mature Appeal,998,CU****,Bronze,10.0,90.0
998,CUST999,Female,36,Electronics,3,50,150,Adult,E,0,High Order,Mid Range,3,33.0,General Appeal,999,CU****,Bronze,5.0,142.5
999,CUST1000,Male,47,Electronics,4,30,120,Senior,E,1,High Order,Mid Range,4,43.5,General Appeal,1000,CU****,Bronze,5.0,114.0

In [43]:
df=pd.read_csv('insurance.csv')
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y
0,22,3,0,High,1
1,35,6,2,Medium,0
2,45,12,7,Low,2
3,28,4,0,High,0
4,51,9,3,Medium,1
5,19,11,6,High,3
6,33,2,0,Low,0
7,42,13,10,Medium,2
8,24,7,1,Low,0
9,38,5,6,High,1

On Insurance Data

Create a UDF that assigns Age Category based on Customer_Age:

<25 → Young
25–45 → Adult
45 → Senior

In [45]:
def Age_category (a):
    if a < 25:
        return 'Young'
    elif 25 <= a <= 45 :
        return 'Adult'
    else:
        return 'Senior'
df['Age_category'] = df['Customer_Age'].apply(Age_category)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category
0,22,3,0,High,1,Young
1,35,6,2,Medium,0,Adult
2,45,12,7,Low,2,Adult
3,28,4,0,High,0,Adult
4,51,9,3,Medium,1,Senior
5,19,11,6,High,3,Young
6,33,2,0,Low,0,Adult
7,42,13,10,Medium,2,Adult
8,24,7,1,Low,0,Young
9,38,5,6,High,1,Adult

Create a UDF that assigns Vehicle Category:

Vehicle_Age < 5 → New
5–10 → Mid Age
10 → Old

In [47]:
def Vehicle_category(v):
    if v < 5 :
        return 'New'
    elif 5 <= v <= 10 :
        return 'Mid Age'
    else:
        return "Old"
df['Vehicle_category'] = df['Vehicle_Age'].apply(Vehicle_category)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category
0,22,3,0,High,1,Young,New
1,35,6,2,Medium,0,Adult,Mid Age
2,45,12,7,Low,2,Adult,Old
3,28,4,0,High,0,Adult,New
4,51,9,3,Medium,1,Senior,Mid Age
5,19,11,6,High,3,Young,Old
6,33,2,0,Low,0,Adult,New
7,42,13,10,Medium,2,Adult,Old
8,24,7,1,Low,0,Young,Mid Age
9,38,5,6,High,1,Adult,Mid Age

Create a UDF that converts Location_Risk into a score:

High → 3
Medium → 2
Low → 1

In [50]:
def Location (Location_Risk):
    if Location_Risk == 'High':
        return 3
    elif Location_Risk == 'Medium':
        return  2
    else:
        return  1
df['Location_Risk_Score'] = df['Location_Risk'].apply(Location)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score
0,22,3,0,High,1,Young,New,3
1,35,6,2,Medium,0,Adult,Mid Age,2
2,45,12,7,Low,2,Adult,Old,1
3,28,4,0,High,0,Adult,New,3
4,51,9,3,Medium,1,Senior,Mid Age,2
5,19,11,6,High,3,Young,Old,3
6,33,2,0,Low,0,Adult,New,1
7,42,13,10,Medium,2,Adult,Old,2
8,24,7,1,Low,0,Young,Mid Age,1
9,38,5,6,High,1,Adult,Mid Age,3

Assignment Level 2 – Medium

Create a UDF that checks Accident Risk:

Accidents_Last_3Y = 0 → Safe Driver
1–2 → Moderate Risk
2 → High Risk

In [52]:
def Accident_Risk (a):
    if a == 0:
        return 'Safe Driver'
    elif 1 <= a <=2:
        return 'Moderate Risk'
    else:
        return 'High Risk'
df['Accident Risk'] = df['Accidents_Last_3Y'].apply(Accident_Risk)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk
0,22,3,0,High,1,Young,New,3,Moderate Risk
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk
3,28,4,0,High,0,Adult,New,3,Safe Driver
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk
5,19,11,6,High,3,Young,Old,3,High Risk
6,33,2,0,Low,0,Adult,New,1,Safe Driver
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk

Create a UDF that classifies claim history:

Claim_History (yrs) = 0 → No Claim History
1–5 → Recent Claims
5 → Long Claim History

In [53]:
def Claim_History (c):
    if c ==0 :
        return 'No Claim History'
    elif 1<= c <= 5 :
        return 'Recent Claims'
    else:
        return 'Long Claim Hsitory'
df['Claim History_Record'] = df['Claim_History (yrs)'].apply(Claim_History)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory


Create a UDF that assigns a flag:

Vehicle Age > 10 AND Location_Risk = High → Critical Vehicle
Otherwise → Normal

In [57]:
def Flag (row):
    if row['Vehicle_Age'] >10 and row['Location_Risk'] == 'High':
        return 'Critical Vehicle'
    else:
        return 'Normal'
df['Flagged_Status'] = df.apply( Flag , axis = 1)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record,Flagged_Status
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History,Normal
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims,Normal
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory,Normal
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History,Normal
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims,Normal
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory,Critical Vehicle
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History,Normal
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory,Normal
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims,Normal
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory,Normal

Assignment Level 3 – Row-Based Logic


Create a UDF to calculate a “Customer Stability Score”:
Formula example:

Score = Customer_Age – (Accidents_Last_3Y × 5)

In [58]:
def customer_score (row):
    return row['Customer_Age']- row['Accidents_Last_3Y']*5
df['Customer_Stability_Score'] = df.apply(customer_score , axis = 1)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record,Flagged_Status,Customer_Stability_Score
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History,Normal,17
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims,Normal,35
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory,Normal,35
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History,Normal,28
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims,Normal,46
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory,Critical Vehicle,4
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History,Normal,33
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory,Normal,32
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims,Normal,24
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory,Normal,33

Create a UDF to calculate “Risk Index” considering:

Higher age adds stability-
More vehicle age increases risk-
More accidents increase risk

Create a UDF that assigns:

High Priority Claim if:

Vehicle_Age > 10 OR Accidents_Last_3Y > 2
Otherwise Regular

In [60]:
def Priority_claim(row):
    if row['Vehicle_Age'] >10 or row['Accidents_Last_3Y'] > 2:
        return 'High Priority'
    else:
        return 'Regular'
df['Priority_Claim_Record'] = df.apply(Priority_claim , axis = 1)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record,Flagged_Status,Customer_Stability_Score,Priority_Claim_Record
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History,Normal,17,Regular
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims,Normal,35,Regular
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory,Normal,35,High Priority
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History,Normal,28,Regular
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims,Normal,46,Regular
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory,Critical Vehicle,4,High Priority
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History,Normal,33,Regular
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory,Normal,32,High Priority
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims,Normal,24,Regular
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory,Normal,33,Regular

Assignment Level 4 – Business Logic

Create a UDF to calculate claim settlement amount factor:
Young + High location risk → factor 1.25
Old + Low risk → factor 0.85
Others → factor 1.0

In [63]:
def amount_factor(row):
    if row['Age_category'] == 'Young' and row['Location_Risk'] == 'High':
        return 1.25
    elif row['Age_category'] == 'Old' and row['Location_Risk'] == 'Low':
        return 0.5
    else:
        return 1.0
df['Settlement_Amount_Factor'] = df.apply(amount_factor, axis=1)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record,Flagged_Status,Customer_Stability_Score,Priority_Claim_Record,Settlement_Amount_Factor
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History,Normal,17,Regular,1.25
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims,Normal,35,Regular,1.00
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory,Normal,35,High Priority,1.00
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History,Normal,28,Regular,1.00
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims,Normal,46,Regular,1.00
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory,Critical Vehicle,4,High Priority,1.25
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History,Normal,33,Regular,1.00
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory,Normal,32,High Priority,1.00
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims,Normal,24,Regular,1.00
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory,Normal,33,Regular,1.00

Create a UDF that determines premium category:
High risk accident + high location → Premium+
Medium combinations → Standard
Otherwise → Basic

In [64]:
def category(row):
    if row['Accident Risk'] == 'High' and row['Location_Risk'] == 'High':
        return 'Premium+'
    elif row['Accident Risk'] == 'Medium' or row['Location_Risk'] == 'Medium':
        return 'Standard'
    else:
        return 'Basic'
df['Premium Category'] = df.apply(category, axis=1)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record,Flagged_Status,Customer_Stability_Score,Priority_Claim_Record,Settlement_Amount_Factor,Premium Category
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History,Normal,17,Regular,1.25,Basic
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims,Normal,35,Regular,1.00,Standard
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory,Normal,35,High Priority,1.00,Basic
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History,Normal,28,Regular,1.00,Basic
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims,Normal,46,Regular,1.00,Standard
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory,Critical Vehicle,4,High Priority,1.25,Basic
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History,Normal,33,Regular,1.00,Basic
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory,Normal,32,High Priority,1.00,Standard
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims,Normal,24,Regular,1.00,Basic
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory,Normal,33,Regular,1.00,Basic

Create a UDF to decide fraud suspicion:
If Claim_History (yrs) > 7 AND Accidents_Last_3Y > 2 → Suspicious
Otherwise Not Suspicious

In [65]:
def fraud_suspicion(row):
    if row['Claim_History (yrs)'] >7 and row['Accidents_Last_3Y'] >2 :
        return 'Suspicious'
    else:
        return 'Not Suspicious'
df['Fraud_suspicion'] = df.apply(fraud_suspicion , axis = 1)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record,Flagged_Status,Customer_Stability_Score,Priority_Claim_Record,Settlement_Amount_Factor,Premium Category,Fraud_suspicion
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History,Normal,17,Regular,1.25,Basic,Not Suspicious
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims,Normal,35,Regular,1.00,Standard,Not Suspicious
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory,Normal,35,High Priority,1.00,Basic,Not Suspicious
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History,Normal,28,Regular,1.00,Basic,Not Suspicious
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims,Normal,46,Regular,1.00,Standard,Not Suspicious
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory,Critical Vehicle,4,High Priority,1.25,Basic,Not Suspicious
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History,Normal,33,Regular,1.00,Basic,Not Suspicious
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory,Normal,32,High Priority,1.00,Standard,Not Suspicious
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims,Normal,24,Regular,1.00,Basic,Not Suspicious
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory,Normal,33,Regular,1.00,Basic,Not Suspicious

Create a UDF that generates a composite Insurance Score:
Scoring must use:
Customer_Age
Vehicle_Age
Claim_History (yrs)
Location_Risk
Accidents_Last_3Y

In [66]:
def calculate_risk(row):
    score = 0
    # Driver Age Risk
    if row['Customer_Age'] < 25:
        score += 30
    elif row['Customer_Age'] <= 40:
        score += 20
    else:
        score += 10

    if row['Vehicle_Age'] > 10:
        score += 25
    elif row['Vehicle_Age'] >= 5:
        score += 15
    else:
        score += 5

    if row['Claim_History (yrs)'] > 5:
        score += 25
    elif row['Claim_History (yrs)'] > 0:
        score += 15

    if row['Location_Risk'] == 'High':
        score += 30
    elif row['Location_Risk'] == 'Medium':
        score += 15
    else:
        score += 5

    # Accidents in last 3 years
    score += row['Accidents_Last_3Y'] * 10

    return score

df['risk score'] = df.apply(calculate_risk, axis=1)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record,Flagged_Status,Customer_Stability_Score,Priority_Claim_Record,Settlement_Amount_Factor,Premium Category,Fraud_suspicion,risk score
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History,Normal,17,Regular,1.25,Basic,Not Suspicious,75
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims,Normal,35,Regular,1.00,Standard,Not Suspicious,65
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory,Normal,35,High Priority,1.00,Basic,Not Suspicious,85
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History,Normal,28,Regular,1.00,Basic,Not Suspicious,55
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims,Normal,46,Regular,1.00,Standard,Not Suspicious,65
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory,Critical Vehicle,4,High Priority,1.25,Basic,Not Suspicious,140
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History,Normal,33,Regular,1.00,Basic,Not Suspicious,30
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory,Normal,32,High Priority,1.00,Standard,Not Suspicious,95
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims,Normal,24,Regular,1.00,Basic,Not Suspicious,65
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory,Normal,33,Regular,1.00,Basic,Not Suspicious,100

Create a UDF that assigns Final Grade based on score:
80 → A
60–80 → B
<60 → C

In [ ]:
def final_grade(score):

    if score >= 80:
        return 'A'
    elif 60 <= score < 80:
        return 'B'
    else:
        return 'C'
df['Final_Grade'] = df['Risk score'].apply(final_grade)
df

Create a UDF to calculate Renewal Probability:
Higher risk → lower probability
Lower risk → higher probability

In [68]:
def renewal_probability(risk):

    if risk == 'High':
        return 0.30
    elif risk == 'Medium':
        return 0.60
    else:
        return 0.8
df['Renewal_Probability'] = df['Location_Risk'].apply(renewal_probability)
df

,Customer_Age,Vehicle_Age,Claim_History (yrs),Location_Risk,Accidents_Last_3Y,Age_category,Vehicle_category,Location_Risk_Score,Accident Risk,Claim History_Record,Flagged_Status,Customer_Stability_Score,Priority_Claim_Record,Settlement_Amount_Factor,Premium Category,Fraud_suspicion,risk score,Renewal_Probability
0,22,3,0,High,1,Young,New,3,Moderate Risk,No Claim History,Normal,17,Regular,1.25,Basic,Not Suspicious,75,0.3
1,35,6,2,Medium,0,Adult,Mid Age,2,Safe Driver,Recent Claims,Normal,35,Regular,1.00,Standard,Not Suspicious,65,0.6
2,45,12,7,Low,2,Adult,Old,1,Moderate Risk,Long Claim Hsitory,Normal,35,High Priority,1.00,Basic,Not Suspicious,85,0.8
3,28,4,0,High,0,Adult,New,3,Safe Driver,No Claim History,Normal,28,Regular,1.00,Basic,Not Suspicious,55,0.3
4,51,9,3,Medium,1,Senior,Mid Age,2,Moderate Risk,Recent Claims,Normal,46,Regular,1.00,Standard,Not Suspicious,65,0.6
5,19,11,6,High,3,Young,Old,3,High Risk,Long Claim Hsitory,Critical Vehicle,4,High Priority,1.25,Basic,Not Suspicious,140,0.3
6,33,2,0,Low,0,Adult,New,1,Safe Driver,No Claim History,Normal,33,Regular,1.00,Basic,Not Suspicious,30,0.8
7,42,13,10,Medium,2,Adult,Old,2,Moderate Risk,Long Claim Hsitory,Normal,32,High Priority,1.00,Standard,Not Suspicious,95,0.6
8,24,7,1,Low,0,Young,Mid Age,1,Safe Driver,Recent Claims,Normal,24,Regular,1.00,Basic,Not Suspicious,65,0.8
9,38,5,6,High,1,Adult,Mid Age,3,Moderate Risk,Long Claim Hsitory,Normal,33,Regular,1.00,Basic,Not Suspicious,100,0.3